-- liquibase formatted sql

-- changeset pozdnyakova-ea:1-15
INSERT INTO "Message_Template" ("Text_Message_Template", "Last_Edit_Date", "Event")
VALUES
    ('Вы хотели бы получать уведомления по этой посылке?', CURRENT_DATE, 'notification'),
    ('Для учета статистики, пожалуйста, укажите, вы являетесь отправителем или получателем этой посылки?', CURRENT_DATE, 'role'),
    ('Совершен выход из режима администратора', CURRENT_DATE, 'exit'),
    ('Вы ввели неверную команду, начните сообщение с символа /', CURRENT_DATE, 'error_command'),
	('Спасибо за предоставление вашего номера телефона!', CURRENT_DATE, 'phone'),
	('Администратор не найден. Для регистрации Вас как администратора, укажите значение токена телеграм-бота.', CURRENT_DATE, 'reg_admin'),
	('Произошла ошибка, пожалуйста, попробуйте снова поделиться номером телефона.', CURRENT_DATE, 'error_phone'),
	('Пожалуйста, укажите номер отслеживания или существующее имя.', CURRENT_DATE, 'error_track'),
	('Имя удалено.', CURRENT_DATE, 'delete_name'),
	('Пожалуйста, укажите удаляемое имя.', CURRENT_DATE, 'error_delete_name'),
	('Такое имя посылки уже создано.', CURRENT_DATE, 'name_exists'),
	('Сохранено.', CURRENT_DATE, 'save'),
	('Пожалуйста, укажите правильный трек-номер и имя для него.', CURRENT_DATE, 'error_add_name'),
	('Пожалуйста, укажите трек-номер и имя.', CURRENT_DATE, 'error_no_track'),
	('Токен введен неверно.', CURRENT_DATE, 'error_token'),
	('Введите почту, на которую будет выслан пароль.', CURRENT_DATE, 'input_email'),
	('Подождите...', CURRENT_DATE, 'wait'),
	('Пароль отправлен на почту.', CURRENT_DATE, 'send'),
	('Данные о вас не найдены в системе, пожалуйста, введите команду /start.', CURRENT_DATE, 'error_user'),
	('Неправильный формат электронной почты. Введите почту правильно.', CURRENT_DATE, 'error_email'),
	('Данные об отслеживании посылки не найдены. Хотите получать уведомления о статусе посылки?', CURRENT_DATE, 'quest_notif'),
	('Посылка доставлена, поменять статус отслеживания нельзя.', CURRENT_DATE, 'delivered'),
	('Посылка отменена, поменять статус отслеживания нельзя.', CURRENT_DATE, 'canceled'),
	('Отмена изменений.', CURRENT_DATE, 'cancel_change'),
	('Адрес почты изменен.', CURRENT_DATE, 'change_email'),
	('Не удалось изменить адрес почты.', CURRENT_DATE, 'error_change_email'),
	('Не удалось изменить пароль.', CURRENT_DATE, 'error_change_password'),
	('Введите пароль.', CURRENT_DATE, 'input_password'),
	('Вы не являетесь администратором.', CURRENT_DATE, 'error_auth'),
	('Вы успешно вошли в режим администратора.', CURRENT_DATE, 'auth'),
	('Неверный пароль.', CURRENT_DATE, 'error_password'),
	('Вы не находитесь в режиме администратора.', CURRENT_DATE, 'error_exit'),
	('Пользователь не найден.', CURRENT_DATE, 'error_find_user'),
	('Пользователь заблокирован, для него нельзя изменить роль.', CURRENT_DATE, 'error_role_blocked'),
	('Данный пользователь является администратором. Изменить его роль на обычного пользователя?', CURRENT_DATE, 'role_admin'),
	('Данный пользователь не является администратором. Изменить его роль на администратора?', CURRENT_DATE, 'role_user'),
	('Введите правильный id пользователя.', CURRENT_DATE, 'error_id'),
	('Такой шаблон не найден.', CURRENT_DATE, 'error_find_template'),
	('Введите id или событие шаблона.', CURRENT_DATE, 'error_id_template'),
	('Шаблон обновлен.', CURRENT_DATE, 'update_template'),
	('Роль пользователя изменена.', CURRENT_DATE, 'update_role'),
	('Ваша роль была изменена с администратора на обычного пользователя.', CURRENT_DATE, 'update_to_user'),
	('Пользователю отправлен запрос на регистрацию.', CURRENT_DATE, 'send_request'),
	('Вас назначили администратором. Введите почту, на которую будет выслан пароль.', CURRENT_DATE, 'update_to_admin'),
	('Выберите промежуток времени для отчета:', CURRENT_DATE, 'select_interval')
;